export const countryState = {
    "Australia": [
        "Australian Capital Territory", 
        "New South Wales", 
        "Northern Territory", 
        "Queensland", 
        "South Australia", 
        "Tasmania", 
        "Victoria", 
        "Western Australia"
    ],
    "UK": [
        "Aberdeen",
        "Aberdeenshire",
        "Angus",
        "Antrim",
        "Antrim and Newtownabbey",
        "Ards",
        "Ards and North Down",
        "Argyll and Bute",
        "Armagh City and District Council",
        "Armagh Banbridge and Craigavon",
        "Ascension Island",
        "Ballymena Borough",
        "Ballymoney",
        "Banbridge",
        "Barnsley",
        "Bath and North East Somerset",
        "Bedford",
        "Belfast district",
        "Birmingham",
        "Blackburn with Darwen",
        "Blackpool",
        "Blaenau Gwent County Borough",
        "Bolton",
        "Bournemouth",
        "Bracknell Forest",
        "Bradford",
        "Bridgend County Borough",
        "Brighton and Hove",
        "Buckinghamshire",
        "Bury",
        "Caerphilly County Borough",
        "Calderdale",
        "Cambridgeshire",
        "Carmarthenshire",
        "Carrickfergus Borough Council",
        "Castlereagh",
        "Causeway Coast and Glens",
        "Central Bedfordshire",
        "Ceredigion",
        "Cheshire East",
        "Cheshire West and Chester",
        "City and County of Cardiff",
        "City and County of Swansea",
        "City of Bristol",
        "City of Derby",
        "City of Kingston upon Hull",
        "City of Leicester",
        "City of London",
        "City of Nottingham",
        "City of Peterborough",
        "City of Plymouth",
        "City of Portsmouth",
        "City of Southampton",
        "City of Stoke-on-Trent",
        "City of Sunderland",
        "City of Westminster",
        "City of Wolverhampton",
        "City of York",
        "Clackmannanshire",
        "Coleraine Borough Council",
        "Conwy County Borough",
        "Cookstown District Council",
        "Cornwall",
        "County Durham",
        "Coventry",
        "Craigavon Borough Council",
        "Cumbria",
        "Darlington",
        "Denbighshire",
        "Derbyshire",
        "Derry City and Strabane",
        "Derry City Council",
        "Devon",
        "Doncaster",
        "Dorset",
        "Down District Council",
        "Dudley",
        "Dumfries and Galloway",
        "Dundee",
        "Dungannon and South Tyrone Borough Council",
        "East Ayrshire",
        "East Dunbartonshire",
        "East Lothian",
        "East Renfrewshire",
        "East Riding of Yorkshire",
        "East Sussex",
        "Edinburgh",
        "England",
        "Essex",
        "Falkirk",
        "Fermanagh and Omagh",
        "Fermanagh District Council",
        "Fife",
        "Flintshire",
        "Gateshead",
        "Glasgow",
        "Gloucestershire",
        "Gwynedd",
        "Halton",
        "Hampshire",
        "Hartlepool",
        "Herefordshire",
        "Hertfordshire",
        "Highland",
        "Inverclyde",
        "Isle of Wight",
        "Isles of Scilly",
        "Kent",
        "Kirklees",
        "Knowsley",
        "Lancashire",
        "Larne Borough Council",
        "Leeds",
        "Leicestershire",
        "Limavady Borough Council",
        "Lincolnshire",
        "Lisburn and Castlereagh",
        "Lisburn City Council",
        "Liverpool",
        "London Borough of Barking and Dagenham",
        "London Borough of Barnet",
        "London Borough of Bexley",
        "London Borough of Brent",
        "London Borough of Bromley",
        "London Borough of Camden",
        "London Borough of Croydon",
        "London Borough of Ealing",
        "London Borough of Enfield",
        "London Borough of Hackney",
        "London Borough of Hammersmith and Fulham",
        "London Borough of Haringey",
        "London Borough of Harrow",
        "London Borough of Havering",
        "London Borough of Hillingdon",
        "London Borough of Hounslow",
        "London Borough of Islington",
        "London Borough of Lambeth",
        "London Borough of Lewisham",
        "London Borough of Merton",
        "London Borough of Newham",
        "London Borough of Redbridge",
        "London Borough of Richmond upon Thames",
        "London Borough of Southwark",
        "London Borough of Sutton",
        "London Borough of Tower Hamlets",
        "London Borough of Waltham Forest",
        "London Borough of Wandsworth",
        "Magherafelt District Council",
        "Manchester",
        "Medway",
        "Merthyr Tydfil County Borough",
        "Metropolitan Borough of Wigan",
        "Mid and East Antrim",
        "Mid Ulster",
        "Middlesbrough",
        "Midlothian",
        "Milton Keynes",
        "Monmouthshire",
        "Moray",
        "Moyle District Council",
        "Neath Port Talbot County Borough",
        "Newcastle upon Tyne",
        "Newport",
        "Newry and Mourne District Council",
        "Newry Mourne and Down",
        "Newtownabbey Borough Council",
        "Norfolk",
        "North Ayrshire",
        "North Down Borough Council",
        "North East Lincolnshire",
        "North Lanarkshire",
        "North Lincolnshire",
        "North Somerset",
        "North Tyneside",
        "North Yorkshire",
        "Northamptonshire",
        "Northern Ireland",
        "Northumberland",
        "Nottinghamshire",
        "Oldham",
        "Omagh District Council",
        "Orkney Islands",
        "Outer Hebrides",
        "Oxfordshire",
        "Pembrokeshire",
        "Perth and Kinross",
        "Poole",
        "Powys",
        "Reading",
        "Redcar and Cleveland",
        "Renfrewshire",
        "Rhondda Cynon Taf",
        "Rochdale",
        "Rotherham",
        "Royal Borough of Greenwich",
        "Royal Borough of Kensington and Chelsea",
        "Royal Borough of Kingston upon Thames",
        "Rutland",
        "Saint Helena",
        "Salford",
        "Sandwell",
        "Scotland",
        "Scottish Borders",
        "Sefton",
        "Sheffield",
        "Shetland Islands",
        "Shropshire",
        "Slough",
        "Solihull",
        "Somerset",
        "South Ayrshire",
        "South Gloucestershire",
        "South Lanarkshire",
        "South Tyneside",
        "Southend-on-Sea",
        "St Helens",
        "Staffordshire",
        "Stirling",
        "Stockport",
        "Stockton-on-Tees",
        "Strabane District Council",
        "Suffolk",
        "Surrey",
        "Swindon",
        "Tameside",
        "Telford and Wrekin",
        "Thurrock",
        "Torbay",
        "Torfaen",
        "Trafford",
        "United Kingdom",
        "Vale of Glamorgan",
        "Wakefield",
        "Wales",
        "Walsall",
        "Warrington",
        "Warwickshire",
        "West Berkshire",
        "West Dunbartonshire",
        "West Lothian",
        "West Sussex",
        "Wiltshire",
        "Windsor and Maidenhead",
        "Wirral",
        "Wokingham",
        "Worcestershire",
        "Wrexham County Borough",
    ],
    "Germany": [
        "Baden-Württemberg",
        "Bavaria",
        "Berlin",
        "Brandenburg",
        "Bremen",
        "Hamburg",
        "Hesse",
        "Lower Saxony",
        "Mecklenburg-Vorpommern",
        "North Rhine-Westphalia",
        "Rhineland-Palatinate",
        "Saarland",
        "Saxony",
        "Saxony-Anhalt",
        "Schleswig-Holstein",
        "Thuringia"      
    ],
    "Ukraine": [
        "Autonomous Republic of Crimea",
        "Cherkaska",
        "Chernihivska",
        "Chernivetska",
        "Dnipropetrovska",
        "Donetska",
        "Ivano-Frankivska",
        "Kharkivska",
        "Khersonska",
        "Khmelnytska",
        "Kirovohradska",
        "Kyivska",
        "Luhanska",
        "Lvivska",
        "Mykolaivska",
        "Odeska",
        "Poltavska",
        "Rivnenska",
        "Sumska",
        "Ternopilska",
        "Vinnytska",
        "Volynska",
        "Zakarpatska",
        "Zaporizka",
        "Zhytomyrska"
    ], 
    "USA": [
        "Alabama",
        "Alaska",
        "American Samoa",
        "Arizona",
        "Arkansas",
        "Baker Island",
        "California",
        "Colorado",
        "Connecticut",
        "Delaware",
        "District of Columbia",
        "Florida",
        "Georgia",
        "Guam",
        "Hawaii",
        "Howland Island",
        "Idaho",
        "Illinois",
        "Indiana",
        "Iowa",
        "Jarvis Island",
        "Johnston Atoll",
        "Kansas",
        "Kentucky",
        "Kingman Reef",
        "Louisiana",
        "Maine",
        "Maryland",
        "Massachusetts",
        "Michigan",
        "Midway Atoll",
        "Minnesota",
        "Mississippi",
        "Missouri",
        "Montana",
        "Navassa Island",
        "Nebraska",
        "Nevada",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "New York",
        "North Carolina",
        "North Dakota",
        "Northern Mariana Islands",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Palmyra Atoll",
        "Pennsylvania",
        "Puerto Rico",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "United States Minor Outlying Islands",
        "United States Virgin Islands",
        "Utah",
        "Vermont",
        "Virginia",
        "Wake Island",
        "Washington",
        "West Virginia",
        "Wisconsin",
        "Wyoming"        
    ]
}


export const countryStateAbbrev = {
    "Australia": [
        "ACT", 
        "NSW", 
        "NT", 
        "QLD", 
        "SA", 
        "TAS", 
        "VIC", 
        "WA"
    ],
    "UK": [
        "ABE",
        "ABD",
        "ANS",
        "ANT",
        "ANN",
        "ARD",
        "AND",
        "AGB",
        "ARM",
        "ABC",
        "SH-AC",
        "BLA",
        "BLY",
        "BNB",
        "BNS",
        "BAS",
        "BDF",
        "BFS",
        "BIR",
        "BBD",
        "BPL",
        "BGW",
        "BOL",
        "BMH",
        "BRC",
        "BRD",
        "BGE",
        "BNH",
        "BKM",
        "BUR",
        "CAY",
        "CLD",
        "CAM",
        "CMN",
        "CKF",
        "CSR",
        "CCG",
        "CBF",
        "CGN",
        "CHE",
        "CHW",
        "CRF",
        "SWA",
        "BST",
        "DER",
        "KHL",
        "LCE",
        "LND",
        "NGM",
        "PTE",
        "PLY",
        "POR",
        "STH",
        "STE",
        "SND",
        "WSM",
        "WLV",
        "YOR",
        "CLK",
        "CLR",
        "CWY",
        "CKT",
        "CON",
        "DUR",
        "COV",
        "CGV",
        "CMA",
        "DAL",
        "DEN",
        "DBY",
        "DRS",
        "DRY",
        "DEV",
        "DNC",
        "DOR",
        "DOW",
        "DUD",
        "DGY",
        "DND",
        "DGN",
        "EAY",
        "EDU",
        "ELN",
        "ERW",
        "ERY",
        "ESX",
        "EDH",
        "ENG",
        "ESS",
        "FAL",
        "FMO",
        "FER",
        "FIF",
        "FLN",
        "GAT",
        "GLG",
        "GLS",
        "GWN",
        "HAL",
        "HAM",
        "HPL",
        "HEF",
        "HRT",
        "HLD",
        "IVC",
        "IOW",
        "IOS",
        "KEN",
        "KIR",
        "KWL",
        "LAN",
        "LRN",
        "LDS",
        "LEC",
        "LMV",
        "LIN",
        "LBC",
        "LSB",
        "LIV",
        "BDG",
        "BNE",
        "BEX",
        "BEN",
        "BRY",
        "CMD",
        "CRY",
        "EAL",
        "ENF",
        "HCK",
        "HMF",
        "HRY",
        "HRW",
        "HAV",
        "HIL",
        "HNS",
        "ISL",
        "LBH",
        "LEW",
        "MRT",
        "NWM",
        "RDB",
        "RIC",
        "SWK",
        "STN",
        "TWH",
        "WFT",
        "WND",
        "MFT",
        "MAN",
        "MDW",
        "MTY",
        "WGN",
        "MEA",
        "MUL",
        "MDB",
        "MLN",
        "MIK",
        "MON",
        "MRY",
        "MYL",
        "NTL",
        "NET",
        "NWP",
        "NYM",
        "NMD",
        "NTA",
        "NFK",
        "NAY",
        "NDN",
        "NEL",
        "NLK",
        "NLN",
        "NSM",
        "NTY",
        "NYK",
        "NTH",
        "NIR",
        "NBL",
        "NTT",
        "OLD",
        "OMH",
        "ORK",
        "ELS",
        "OXF",
        "PEM",
        "PKN",
        "POL",
        "POW",
        "RDG",
        "RCC",
        "RFW",
        "RCT",
        "RCH",
        "ROT",
        "GRE",
        "KEC",
        "KTT",
        "RUT",
        "SH-HL",
        "SLF",
        "SAW",
        "SCT",
        "SCB",
        "SFT",
        "SHF",
        "ZET",
        "SHR",
        "SLG",
        "SOL",
        "SOM",
        "SAY",
        "SGC",
        "SLK",
        "STY",
        "SOS",
        "SHN",
        "STS",
        "STG",
        "SKP",
        "STT",
        "STB",
        "SFK",
        "SRY",
        "SWD",
        "TAM",
        "TFW",
        "THR",
        "TOB",
        "TOF",
        "TRF",
        "UKM",
        "VGL",
        "WKF",
        "WLS",
        "WLL",
        "WRT",
        "WAR",
        "WBK",
        "WDU",
        "WLN",
        "WSX",
        "WIL",
        "WNM",
        "WRL",
        "WOK",
        "WOR",
        "WRX",    
    ],
    "Germany": [
        "BW",
        "BY",
        "BE",
        "BB",
        "HB",
        "HH",
        "HE",
        "NI",
        "MV",
        "NW",
        "RP",
        "SL",
        "SN",
        "ST",
        "SH",
        "TH",
    ],
    "Ukraine": [
        "ARC",
        "CK",
        "CH",
        "CV",
        "DP",
        "DT",
        "IF",
        "KK",
        "KS",
        "KM",
        "KH",
        "KV",
        "LH",
        "LV",
        "MY",
        "OD",
        "PL",
        "RV",
        "SM",
        "TP",
        "VI",
        "VO",
        "ZK",
        "ZP",
        "ZT"        
    ], 
    "USA": [
        "AL",
        "AK",
        "AS",
        "AZ",
        "AR",
        "UM-81",
        "CA",
        "CO",
        "CT",
        "DE",
        "DC",
        "FL",
        "GA",
        "GU",
        "HI",
        "UM-84",
        "ID",
        "IL",
        "IN",
        "IA",
        "UM-86",
        "UM-67",
        "KS",
        "KY",
        "UM-89",
        "LA",
        "ME",
        "MD",
        "MA",
        "MI",
        "UM-71",
        "MN",
        "MS",
        "MO",
        "MT",
        "UM-76",
        "NE",
        "NV",
        "NH",
        "NJ",
        "NM",
        "NY",
        "NC",
        "ND",
        "MP",
        "OH",
        "OK",
        "OR",
        "UM-95",
        "PA",
        "PR",
        "RI",
        "SC",
        "SD",
        "TN",
        "TX",
        "UM",
        "VI",
        "UT",
        "VT",
        "VA",
        "UM-79",
        "WA",
        "WV",
        "WI",
        "WY",        
    ]
}